on: [push]
permissions:
  contents: write
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: foo
        uses: github-actions-publish/publish-action@main
        with:
          tag: v1
